//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonWay.TechnicalTest.Consumer {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LemonWay.TechnicalTest.Consumer.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Call to Finobacci method with value ({0}).
        /// </summary>
        internal static string Finobacci_CallMethod {
            get {
                return ResourceManager.GetString("Finobacci_CallMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The parameter for the calcul of Finobacci sequence must be an integer.
        /// </summary>
        internal static string Finobacci_WrongparameterType {
            get {
                return ResourceManager.GetString("Finobacci_WrongparameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Call to FinobacciWithError method with value ({0}).
        /// </summary>
        internal static string FinobacciWithError_CallMethod {
            get {
                return ResourceManager.GetString("FinobacciWithError_CallMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error Code : {0}.
        /// </summary>
        internal static string MethodErrorCode {
            get {
                return ResourceManager.GetString("MethodErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error Message : {0}.
        /// </summary>
        internal static string MethodErrorMessage {
            get {
                return ResourceManager.GetString("MethodErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Result : {0}.
        /// </summary>
        internal static string MethodResult {
            get {
                return ResourceManager.GetString("MethodResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can make your own call by writting the method you want to call and the necessary parameter, separated by a whitespace. To leave the application, only type the enter key. Ex : &quot;Finobacci 10&quot; or &quot;XmlToJsonWithError &lt;Test&gt;myTest&lt;/Test&gt;&quot;.
        /// </summary>
        internal static string ServiceMethods_OwnCall {
            get {
                return ResourceManager.GetString("ServiceMethods_OwnCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unexpected error occured, please try again.
        /// </summary>
        internal static string ServiceMethods_UnexpectedError {
            get {
                return ResourceManager.GetString("ServiceMethods_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your request is invalid. Please check it and try again.
        /// </summary>
        internal static string ServiceMethods_WrongParameterNumber {
            get {
                return ResourceManager.GetString("ServiceMethods_WrongParameterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Call to XmlToJson method with xml ({0}).
        /// </summary>
        internal static string XmlToJson_CallMethod {
            get {
                return ResourceManager.GetString("XmlToJson_CallMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Call to XmlToJsonWith method with xml ({0}).
        /// </summary>
        internal static string XmlToJsonWithError_CallMethod {
            get {
                return ResourceManager.GetString("XmlToJsonWithError_CallMethod", resourceCulture);
            }
        }
    }
}
